### PR TITLE
fix: settle now reminder correctly shows it user owes something.

### LINKED ISSUE #377: Ask to settle gives wrong message on receiver side
Ask to settle button generates the message "all settled"
Screenshot 2023-09-12 at 11 43 27

### PR DESCRIPTION
**Pull request by vojtechsimetka**
resolves #377

### CODE REVIEW

File: src/lib/objects/split/chat-messages/settle-reminder.svelte [hunk 1]
```diff
@@ -72,7 +72,8 @@
 			</Container>
 		</div>
 	</ChatMessage>
-{:else if paid || owedAmount > 0n}
+{:else if paid || owedAmount <= 0n}
```
Comment (agazso) [inline src/lib/objects/split/chat-messages/settle-reminder.svelte:75]: `paid` is always false in this file, can it be removed?

Comment (vojtechsimetka) [reply src/lib/objects/split/chat-messages/settle-reminder.svelte]: nice catch, removed thanks!

**Review by agazso — APPROVED** [review]
