### PR TITLE
fix: payggy default token balance

### LINKED ISSUE #286: When sending tokens (Payggy), the xDai balance shows as 0 until after re-selecting the token from the dropdown

### PR DESCRIPTION
**Pull request by agazso**
Fixes #286

### CODE REVIEW

File: src/lib/objects/payggy/standalone.svelte [hunk 1]
```diff
@@ -54,9 +53,8 @@
 	let token: Token
 	let amount = ''
 	let fee: Token | undefined = undefined
-	const nativeToken = defaultBlockchainNetwork.nativeToken
 
-	$: if (!token) token = nativeToken
+	$: if (!token) token = args.tokens[0]
```
Comment (vojtechsimetka) [inline src/lib/objects/payggy/standalone.svelte:57]:
```suggestion
	$: if (!token) token = args.tokens.find(t => t.address === undefined) ?? tokens[0]
```

**Review by vojtechsimetka — APPROVED** [review]
I'd prefer to always have native token to be selected. Otherwise LGTM
